# Generated by Django 5.2.5 on 2025-11-03 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("indicators", "0005_indicator_source_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="indicator",
            name="use_in_express_interface",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if the indicator is used in the Express Interface",
                verbose_name="Use in Express Interface",
            ),
        ),
    ]
