# Generated by Django 5.2.5 on 2025-11-11 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("indicators", "0006_indicator_use_in_express_interface"),
    ]

    operations = [
        migrations.CreateModel(
            name="USStateIndicator",
            fields=[],
            options={
                "verbose_name": "US State Indicator",
                "verbose_name_plural": "US State Indicators",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("indicators.indicator",),
        ),
    ]
