# Generated by Django 5.2.5 on 2026-04-28 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_alter_geography_options"),
        ("datasources", "0003_alter_sourcesubdivision_source_type"),
        ("indicators", "0008_alter_indicator_source_type"),
        ("indicatorsets", "0008_alter_indicatorset_documentation_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="indicator",
            name="base",
        ),
        migrations.AlterField(
            model_name="indicator",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="indicators",
                to="indicators.category",
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="indicator",
            name="format_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="indicators",
                to="indicators.formattype",
                verbose_name="Format Type",
            ),
        ),
        migrations.AlterField(
            model_name="indicator",
            name="geographic_scope",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="indicators",
                to="base.geographicscope",
                verbose_name="Geographic Scope",
            ),
        ),
        migrations.AlterField(
            model_name="indicator",
            name="indicator_set",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="indicators",
                to="indicatorsets.indicatorset",
                verbose_name="Indicator Set",
            ),
        ),
        migrations.AlterField(
            model_name="indicator",
            name="indicator_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="indicators",
                to="indicators.indicatortype",
                verbose_name="Indicator Type",
            ),
        ),
        migrations.AlterField(
            model_name="indicator",
            name="source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="indicators",
                to="datasources.sourcesubdivision",
                verbose_name="Source Subdivision",
            ),
        ),
    ]
