# Generated by Django 5.2.5 on 2025-10-10 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="geography",
            options={
                "ordering": ["display_order_number"],
                "verbose_name": "Geography",
                "verbose_name_plural": "Geographies",
            },
        ),
    ]
