# Generated by Django 5.2.5 on 2026-10-05 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_alter_geography_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        help_text='Shown as written, HTML included, so links can be added with <code>&lt;a href="..."&gt;</code>.',
                        verbose_name="Message",
                    ),
                ),
                (
                    "style",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("danger", "Danger"),
                        ],
                        default="info",
                        max_length=16,
                        verbose_name="Style",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "starts_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Leave empty to show it straight away.",
                        null=True,
                        verbose_name="Starts at",
                    ),
                ),
                (
                    "ends_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Leave empty to show it until it is switched off.",
                        null=True,
                        verbose_name="Ends at",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Banner",
                "verbose_name_plural": "Banners",
                "ordering": ["-created_at"],
            },
        ),
    ]
