# Generated by Django 5.2.5 on 2025-11-28 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("indicators", "0008_alter_indicator_source_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpressViewIndicator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "menu_item",
                    models.CharField(max_length=255, verbose_name="Menu Item"),
                ),
                (
                    "display_name",
                    models.CharField(max_length=255, verbose_name="Display Name"),
                ),
                (
                    "indicator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="indicators.indicator",
                        verbose_name="Indicator",
                    ),
                ),
            ],
            options={
                "verbose_name": "Express View Indicator",
                "verbose_name_plural": "Express View Indicators",
                "ordering": ["menu_item", "indicator"],
                "indexes": [
                    models.Index(
                        fields=["menu_item", "indicator"], name="expr_view_ind_menu_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("menu_item", "indicator"),
                        name="uniq_expr_view_menu_ind",
                    )
                ],
            },
        ),
    ]
