# Generated by Django 5.2.5 on 2025-12-18 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alternative_interface", "0001_initial"),
        ("indicators", "0008_alter_indicator_source_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expressviewindicator",
            name="indicator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="indicators.indicator",
                verbose_name="Indicator",
            ),
        ),
    ]
