# Generated by Django 5.2.5 on 2025-12-18 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alternative_interface", "0002_alter_expressviewindicator_indicator"),
    ]

    operations = [
        migrations.AddField(
            model_name="expressviewindicator",
            name="grouping_key",
            field=models.CharField(
                blank=True,
                help_text="Key to group indicators for scaling",
                max_length=255,
                verbose_name="Grouping Key",
            ),
        ),
    ]
