# Generated by Django 5.2.5 on 2025-12-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alternative_interface", "0003_expressviewindicator_grouping_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="expressviewindicator",
            name="display_order",
            field=models.IntegerField(
                default=0,
                help_text="Order to display the indicator in the legend",
                verbose_name="Display Order",
            ),
        ),
    ]
