COVIDCAST_FLUVIEW_LOCATIONS_MAPPING = {
    "nation:US": "nat",
    "hhs:1": "hhs1",
    "hhs:2": "hhs2",
    "hhs:3": "hhs3",
    "hhs:4": "hhs4",
    "hhs:5": "hhs5",
    "hhs:6": "hhs6",
    "hhs:7": "hhs7",
    "hhs:8": "hhs8",
    "hhs:9": "hhs9",
    "hhs:10": "hhs10",
    "state:AK": "AK",
    "state:AL": "AL",
    "state:AR": "AR",
    "state:AZ": "AZ",
    "state:CA": "CA",
    "state:CO": "CO",
    "state:CT": "CT",
    "state:DC": "DC",
    "state:DE": "DE",
    "state:FL": "FL",
    "state:GA": "GA",
    "state:HI": "HI",
    "state:IA": "IA",
    "state:ID": "ID",
    "state:IL": "IL",
    "state:IN": "IN",
    "state:KS": "KS",
    "state:KY": "KY",
    "state:LA": "LA",
    "state:MA": "MA",
    "state:MD": "MD",
    "state:ME": "ME",
    "state:MI": "MI",
    "state:MN": "MN",
    "state:MO": "MO",
    "state:MS": "MS",
    "state:MT": "MT",
    "state:NC": "NC",
    "state:ND": "ND",
    "state:NE": "NE",
    "state:NH": "NH",
    "state:NJ": "NJ",
    "state:NM": "NM",
    "state:NV": "NV",
    "state:NY": "NY",
    "state:OH": "OH",
    "state:OK": "OK",
    "state:OR": "OR",
    "state:PA": "PA",
    "state:RI": "RI",
    "state:SC": "SC",
    "state:SD": "SD",
    "state:TN": "TN",
    "state:TX": "TX",
    "state:UT": "UT",
    "state:VA": "VA",
    "state:VT": "VT",
    "state:WA": "WA",
    "state:WI": "WI",
    "state:WV": "WV",
    "state:WY": "WY",
    # fluview (ILINET) specific locations
    "ny_minus_jfk:ny_minus_jfk": "NY (minus NYC)",
    "us-territory:as": "American Samoa",
    "us-territory:mp": "Mariana Islands",
    "us-territory:gu": "Guam",
    "us-territory:pr": "Puerto Rico",
    "us-territory:vi": "Virgin Islands",
    "us-city:ord": "Chicago",
    "us-city:lax": "Los Angeles",
    "us-city:jfk": "New York City",
}

