COVIDCAST_FLUVIEW_LOCATIONS_MAPPING = {
    "nation:US": "nat",
    "hhs:1": "hhs1",
    "hhs:2": "hhs2",
    "hhs:3": "hhs3",
    "hhs:4": "hhs4",
    "hhs:5": "hhs5",
    "hhs:6": "hhs6",
    "hhs:7": "hhs7",
    "hhs:8": "hhs8",
    "hhs:9": "hhs9",
    "hhs:10": "hhs10",
    "state:AK": "AK",
    "state:AL": "AL",
    "state:AR": "AR",
    "state:AZ": "AZ",
    "state:CA": "CA",
    "state:CO": "CO",
    "state:CT": "CT",
    "state:DC": "DC",
    "state:DE": "DE",
    "state:FL": "FL",
    "state:GA": "GA",
    "state:HI": "HI",
    "state:IA": "IA",
    "state:ID": "ID",
    "state:IL": "IL",
    "state:IN": "IN",
    "state:KS": "KS",
    "state:KY": "KY",
    "state:LA": "LA",
    "state:MA": "MA",
    "state:MD": "MD",
    "state:ME": "ME",
    "state:MI": "MI",
    "state:MN": "MN",
    "state:MO": "MO",
    "state:MS": "MS",
    "state:MT": "MT",
    "state:NC": "NC",
    "state:ND": "ND",
    "state:NE": "NE",
    "state:NH": "NH",
    "state:NJ": "NJ",
    "state:NM": "NM",
    "state:NV": "NV",
    "state:NY": "NY",
    "state:OH": "OH",
    "state:OK": "OK",
    "state:OR": "OR",
    "state:PA": "PA",
    "state:RI": "RI",
    "state:SC": "SC",
    "state:SD": "SD",
    "state:TN": "TN",
    "state:TX": "TX",
    "state:UT": "UT",
    "state:VA": "VA",
    "state:VT": "VT",
    "state:WA": "WA",
    "state:WI": "WI",
    "state:WV": "WV",
    "state:WY": "WY",
}

EXPRESS_VIEW_LABELS_MAPPING = {
    "smoothed_pct_ed_visits_influenza": "Influenza emergency department visits (NSSP)",
    "confirmed_admissions_flu_ew": "Influenza hospital admissions (NHSN)",
    "percent_positive": "Test positivity for influenza (ILINet)",
    "percent_a": "Test positivity for influenza A (ILINet)",
    "percent_b": "Test positivity for influenza B (ILINet)",
    "smoothed_flu_from_claims": "Influenza hospital admissions (from claims)",
    "deaths_flu_incidence_num": "Influenza deaths (NCHS)",
    "smoothed_cli": "Covid related doctor visits (from claims)",
    "smoothed_pct_ed_visits_covid": "Covid emergency department visits (NSSP)",
    "confirmed_admissions_covid_ew": "Covid hospital admissions (NHNS)",
    "smoothed_covid19_from_claims": "Covid hospital admissions (from claims)",
    "deaths_covid_incidence_num": "Covid deaths (NCHS)",
    "pct_ed_visits_rsv": "RSV emergency department visits (NSSP)",
    "confirmed_admissions_rsv_ew": "RSV hospital admissions (NHSN)",
    "pct_ed_visits_combined": "Combined emergency department visits (NSSP)",
    "wili": "ILI related doctor visits (ILINet)",
    "deaths_pneumonia_or_flu_or_covid_incidence_num": "Deaths from flu, Covid or pneumonia (NCHS)",
}
