# Generated by Django 5.2.5 on 2025-08-27 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("indicatorsets", "0004_columndescription_filterdescription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indicatorset",
            name="source_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("covidcast", "Covidcast"),
                    ("other_endpoint", "Other Endpoint"),
                    ("non_delphi", "Non Delphi"),
                ],
                default="covidcast",
                help_text="Type of source for the indicator set",
                max_length=255,
                null=True,
                verbose_name="Source Type",
            ),
        ),
    ]
