# Generated by Django 5.2.5 on 2025-11-11 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("indicatorsets", "0005_alter_indicatorset_source_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="USStateIndicatorSet",
            fields=[],
            options={
                "verbose_name": "US State Indicator Set",
                "verbose_name_plural": "US State Indicators Sets",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("indicatorsets.indicatorset",),
        ),
        migrations.AddField(
            model_name="indicatorset",
            name="state",
            field=models.CharField(
                blank=True,
                help_text="State of the indicator set",
                max_length=255,
                verbose_name="State",
            ),
        ),
    ]
