# Generated by Django 5.2.5 on 2025-12-18 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("indicatorsets", "0007_alter_indicatorset_source_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indicatorset",
            name="documentation_link",
            field=models.CharField(
                blank=True,
                help_text="Link to the documentation for the Indicator Set",
                max_length=500,
                verbose_name="Documentation Link",
            ),
        ),
    ]
