# Generated by Django 5.2.5 on 2026-04-28 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_alter_geography_options"),
        ("indicatorsets", "0008_alter_indicatorset_documentation_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indicatorset",
            name="geographic_scope",
            field=models.ForeignKey(
                blank=True,
                help_text="Geographic scope of the Indicator Set",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="indicator_sets",
                to="base.geographicscope",
                verbose_name="Geographic Scope",
            ),
        ),
    ]
