# Generated by Django 5.2.5 on 2026-06-16 20:35

from django.db import migrations


INDICATOR_SET_TABLE = "indicatorsets_indicatorset"
PROVIDER_TABLE = "indicatorsets_originaldataprovider"
CHAR_COLUMN = "original_data_provider"
FK_COLUMN = "original_data_provider_id"


def _get_indicator_set_columns(cursor):
    cursor.execute(
        """
        SELECT COLUMN_NAME, DATA_TYPE
        FROM information_schema.COLUMNS
        WHERE TABLE_SCHEMA = DATABASE()
          AND TABLE_NAME = %s
        """,
        [INDICATOR_SET_TABLE],
    )
    return {row[0]: row[1] for row in cursor.fetchall()}


def _table_exists(cursor, table_name):
    cursor.execute("SHOW TABLES LIKE %s", [table_name])
    return cursor.fetchone() is not None


def _drop_foreign_keys(cursor):
    cursor.execute(
        """
        SELECT CONSTRAINT_NAME
        FROM information_schema.KEY_COLUMN_USAGE
        WHERE TABLE_SCHEMA = DATABASE()
          AND TABLE_NAME = %s
          AND COLUMN_NAME = %s
          AND REFERENCED_TABLE_NAME IS NOT NULL
        """,
        [INDICATOR_SET_TABLE, FK_COLUMN],
    )
    for (constraint_name,) in cursor.fetchall():
        cursor.execute(
            f"ALTER TABLE `{INDICATOR_SET_TABLE}` DROP FOREIGN KEY `{constraint_name}`"
        )


def revert_original_data_provider_schema(apps, schema_editor):
    """
    Ensure DB matches CharField original_data_provider with no ODP lookup table.

    Handles fresh DBs, orphan ODP tables from failed deploys, and FK-based schemas.
    """
    with schema_editor.connection.cursor() as cursor:
        if not _table_exists(cursor, INDICATOR_SET_TABLE):
            return

        columns = _get_indicator_set_columns(cursor)
        has_char = CHAR_COLUMN in columns
        has_fk = FK_COLUMN in columns
        has_provider_table = _table_exists(cursor, PROVIDER_TABLE)

        cursor.execute("SET FOREIGN_KEY_CHECKS=0")

        if has_fk:
            if has_provider_table:
                if not has_char:
                    cursor.execute(
                        f"ALTER TABLE `{INDICATOR_SET_TABLE}` "
                        f"ADD COLUMN `{CHAR_COLUMN}` varchar(255) NOT NULL DEFAULT ''"
                    )
                    has_char = True

                cursor.execute(
                    f"""
                    UPDATE `{INDICATOR_SET_TABLE}` iset
                    LEFT JOIN `{PROVIDER_TABLE}` odp
                      ON iset.`{FK_COLUMN}` = odp.`id`
                    SET iset.`{CHAR_COLUMN}` = COALESCE(odp.`name`, '')
                    """
                )

            _drop_foreign_keys(cursor)
            cursor.execute(
                f"ALTER TABLE `{INDICATOR_SET_TABLE}` DROP COLUMN `{FK_COLUMN}`"
            )

        if has_provider_table:
            cursor.execute(f"DROP TABLE IF EXISTS `{PROVIDER_TABLE}`")

        cursor.execute("SET FOREIGN_KEY_CHECKS=1")


class Migration(migrations.Migration):

    dependencies = [
        ("indicatorsets", "0009_alter_indicatorset_geographic_scope"),
    ]

    operations = [
        migrations.RunPython(
            revert_original_data_provider_schema,
            migrations.RunPython.noop,
        ),
    ]
