# Generated by Django 5.2.5 on 2026-06-16 20:35

import django.db.models.deletion
from django.db import migrations, models


def drop_orphan_original_data_provider_table(apps, schema_editor):
    """Clean up partial/failed deploys before CreateModel runs."""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("SET FOREIGN_KEY_CHECKS=0")
        cursor.execute(
            """
            SELECT CONSTRAINT_NAME
            FROM information_schema.KEY_COLUMN_USAGE
            WHERE TABLE_SCHEMA = DATABASE()
              AND TABLE_NAME = 'indicatorsets_indicatorset'
              AND COLUMN_NAME = 'original_data_provider_id'
              AND REFERENCED_TABLE_NAME IS NOT NULL
            """
        )
        for (constraint_name,) in cursor.fetchall():
            cursor.execute(
                f"ALTER TABLE `indicatorsets_indicatorset` "
                f"DROP FOREIGN KEY `{constraint_name}`"
            )
        cursor.execute("DROP TABLE IF EXISTS `indicatorsets_originaldataprovider`")
        cursor.execute("SET FOREIGN_KEY_CHECKS=1")


class Migration(migrations.Migration):

    dependencies = [
        ("indicatorsets", "0009_alter_indicatorset_geographic_scope"),
    ]

    operations = [
        migrations.RunPython(
            drop_orphan_original_data_provider_table,
            migrations.RunPython.noop,
        ),
        migrations.CreateModel(
            name="OriginalDataProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="Name"),
                ),
                (
                    "group",
                    models.CharField(
                        choices=[
                            ("us_government", "U.S. Government"),
                            ("us_states", "U.S. States"),
                            ("individual", "Individual providers"),
                        ],
                        default="individual",
                        max_length=32,
                        verbose_name="Group",
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(default=0, verbose_name="Display Order"),
                ),
            ],
            options={
                "verbose_name": "Original Data Provider",
                "verbose_name_plural": "Original Data Providers",
                "ordering": ["display_order"],
                "indexes": [
                    models.Index(fields=["name"], name="data_provider_name_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name", "group"), name="unique_data_provider_name_group"
                    )
                ],
            },
        ),
        migrations.AlterField(
            model_name="indicatorset",
            name="original_data_provider",
            field=models.ForeignKey(
                blank=True,
                help_text="Original data provider of the Indicator Set",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="indicator_sets",
                to="indicatorsets.originaldataprovider",
                verbose_name="Original Data Provider",
            ),
        ),
    ]
