# Generated by Django 5.2.5 on 2026-06-16 22:27

from django.db import migrations, models


def copy_provider_names_to_char(apps, schema_editor):
    IndicatorSet = apps.get_model("indicatorsets", "IndicatorSet")
    OriginalDataProvider = apps.get_model("indicatorsets", "OriginalDataProvider")
    provider_names = dict(
        OriginalDataProvider.objects.values_list("id", "name")
    )

    for indicator_set in IndicatorSet.objects.all().iterator():
        provider_id = indicator_set.original_data_provider_id
        name = provider_names.get(provider_id, "") if provider_id else ""
        IndicatorSet.objects.filter(pk=indicator_set.pk).update(
            original_data_provider_text=name
        )


class Migration(migrations.Migration):

    dependencies = [
        ("indicatorsets", "0010_originaldataprovider_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="indicatorset",
            name="original_data_provider_text",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Original data provider of the Indicator Set",
                max_length=255,
                verbose_name="Original Data Provider",
            ),
        ),
        migrations.RunPython(
            copy_provider_names_to_char,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="indicatorset",
            name="original_data_provider",
        ),
        migrations.RenameField(
            model_name="indicatorset",
            old_name="original_data_provider_text",
            new_name="original_data_provider",
        ),
        migrations.DeleteModel(
            name="OriginalDataProvider",
        ),
    ]
