# Generated by Django 5.2.5 on 2026-06-16 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("indicatorsets", "0010_originaldataprovider_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indicatorset",
            name="original_data_provider",
            field=models.CharField(
                blank=True,
                default="null",
                help_text="Original data provider of the Indicator Set",
                max_length=255,
                verbose_name="Original Data Provider",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="OriginalDataProvider",
        ),
    ]
