# Generated by Django 5.2.5 on 2025-08-27 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datasources", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OtherEndpointSourceSubdivision",
            fields=[],
            options={
                "verbose_name": "Other Endpoint Source Subdivision",
                "verbose_name_plural": "Other Endpoint Source Subdivisions",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("datasources.sourcesubdivision",),
        ),
        migrations.AddField(
            model_name="sourcesubdivision",
            name="source_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("covidcast", "Covidcast"),
                    ("other_endpoint", "Other Endpoint"),
                    ("non_delphi", "Non Delphi"),
                ],
                default="covidcast",
                help_text="Type of source for the source subdivision",
                max_length=255,
                null=True,
                verbose_name="Source Type",
            ),
        ),
    ]
