# Generated by Django 5.2.5 on 2025-11-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datasources", "0002_otherendpointsourcesubdivision_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sourcesubdivision",
            name="source_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("covidcast", "Covidcast"),
                    ("other_endpoint", "Other Endpoint"),
                    ("non_delphi", "Non Delphi"),
                    ("us_state", "US State"),
                ],
                default="covidcast",
                help_text="Type of source for the source subdivision",
                max_length=255,
                null=True,
                verbose_name="Source Type",
            ),
        ),
    ]
